---
title: "Habitación 7:"
include-in-header:
  text: |
    <script type="module">
    window.GLOBAL_URL = "https://raw.githubusercontent.com/sebastiandres/pyscape/refs/heads/main/quarto/rooms/sala_07.py";
    </script>
    <style>
    #quarto-sidebar, #quarto-sidebar-container { display: none !important; }
    </style>
---

Desde el módulo de control, detectan múltiples objetos orbitando alrededor de la estación espacial. Es urgente
analizar sus coordenadas para prevenir colisiones. Necesitas ordenar las coordenadas y extraer tres datos clave:

- El objeto más cercano a la estación.
- El objeto más lejano.
- El objeto que se encuentra en el centro de la lista (una vez ordenada).

<div class="alert alert-info">
Ordena la `lista` ocupando la función `.sorted()` y utilizando los `indices` necesarios para crear una nueva
lista con las coordenadas requeridas.
</div>

::: {.callout-tip title="Pista" collapse="true"}
El valor del **centro** depende del largo de la lista:

- Si el largo de la lista es un número par: Es el valor **entero** del promedio de los valores que están al medio.
- Si el lago de la lista es un número impar: Es el valor de al medio.

```python
largo = len(lista)
valor = lista(largo//2) # Para lista con largo impar
```
La operación `//2` es una división que obtiene sólo el valor entero del resultado. Si es `7//2` obtiene el valor de 3.

:::

```{pyodide-python}
coordenadas = [540, 320, 890, 150, 430, 270]

# Escribe tu respuesta aquí
respuesta = None
print(respuesta)

# Verifica la respuesta
import sala
sala.revisar(respuesta)
```