---
title: "Habitación 10:"
include-in-header:
  text: |
    <script type="module">
    window.GLOBAL_URL = "https://raw.githubusercontent.com/sebastiandres/pyscape/refs/heads/main/quarto/rooms/sala_10.py";
    </script>
    <style>
    #quarto-sidebar, #quarto-sidebar-container { display: none !important; }
    </style>
---

Hay problemas con el sistema de reconocimiento de objetos espaciales, no reconoce ciertos formatos de los textos.

Para corregir el texto, se debe cambiar a mayúsculas o minúsculas según sea uno de los siguientes casos:

- Si la variable `palabra` contiene **meteorito**, debe quedar en minúsculas.
- Si la variable `palabra` contiene **asteroide**, debe quedar en mayúsculas.

<div class="alert alert-info">
Se deben ocupar las funciones `.upper()` para convertir el texto en mayúsculas o `.lower()` para convertir
el texto en minúsculas.

Por ejemplo para convertir en minúsculas:
```python
palabra_origial = "PySchool"
palabra_original.lower()
```
También para verificar que un texto contiene una cierta palabra, se debe ocupar `in` en la sentencia `if`,
pero cuidado que esto es sensible a las letras en mayúsculas o minúsculas, es decir, no es lo mismo **Meteorito** que **meteorito**.
</div>

::: {.callout-tip title="Pista" collapse="true"}
Seguir el ejemplo para saber si una variable contiene la palabra **pyschool**

```python 
variable_uno = "pyschool 2025"
variable_dos = "hola 2025"

def convertir_mayuscula(palabra):
    if "pyschool" in palabra:
        return palabra.upper()

convertir_mayuscula(variable_uno)
convertir_mayuscula(variable_dos)
```
:::

```{pyodide-python}
# Palabras de ejemplo:
# asteroide urania, leda asteroide, meteorito arlong, dronino meteorito

def transformar_palabras(palabra):
    # Escribe aquí tus sentencias if

# Verifica la respuesta
import sala
sala.revisar(transformar_palabras)
```