---
title: "Habitación 17:"
include-in-header:
  text: |
    <script type="module">
    window.GLOBAL_URL = "https://raw.githubusercontent.com/sebastiandres/pyschool_2025/refs/heads/main/quarto/rooms/sala_17.py";
    </script>
    <style>
    #quarto-sidebar, #quarto-sidebar-container { display: none !important; }
    </style>
---

El equipo ha llegado al núcleo de la estación espacial. Se encuentra una compuerta antes de llegar a la sala final, pero está
bloqueada y se necesita conocer la contraseña para que se pueda abrir.

La contraseña se puede conocer ocupando el código secreto en la suma de los números primos requeridos.

<div class="alert alert-info">
Obtén la suma desde el primer número primo hasta el indicado en el `código secreto`. Ten en consideración que se debe recorrer todos
los números enteros positivos y en caso que cumpla con ser número primo, sumarlo, así sucesivamente hasta obtener la suma total.

Por ejemplo:

```python
def es_primo(numero):
    if numero % 1 == 0:
        return True
    elif numero % 2 == 0:
        return False
    elif numero % 3 == 0:
        return False
    elif numero % numero == 0:
        return True

for numero in numeros:
    if es_primo(numero):
        suma = suma + numero
```
</div>

::: {.callout-tip title="Pista" collapse="true"}
Considera lo siguiente para el algoritmo de la suma de los primeros `N` números primos:

- Para saber si es un número primo, debe ser divisible por el número 1 y por si mismo. Ejemplo: `A % 1 == 0`  y `A % A == 0`.
- Crear variable que cuente cuántos números primos se han sumado, sin que pase el valor del `código secreto`.
- Crear variable que vaya acumulando la suma de los primeros `N` números primos.

```python
suma = 0
contador_numeros = 0
for numero in numeros:
    if es_primo(numero):
        suma = suma + numero
        contador_numeros = contador_numeros + 1
```

:::

```{pyodide-python}

# Escribe aquí función para saber si un número es primo

# Escribe tu respuesta
respuesta = None
print(respuesta)

# Verifica la respuesta
import sala
sala.revisar(respuesta)
```