# Basic Metadata Configuration
title: "PySchool 2025"
#subtitle: "Un escape room con Python: Aprende Python mientras resuelves desafíos"
#description: "Aprende Python mientras resuelves desafíos"
#author: "Sebastian Flores"
#date: "2025-05-04"
lang: es
license: "CC BY-NC"

# Project Configuration
project:
  type: book
  output-dir: "../docs"

# Book Configuration
book:
  #sidebar: false        # show sidebar navigation
  #reader-mode: true    # focuses content (like Read the Docs)
  favicon: "images/favicon.png"
  chapters:
    - index.qmd
    - index2.qmd
    - pyschool.qmd
    - rooms/sala_00.qmd
    - rooms/sala_01.qmd
    - rooms/sala_02.qmd
    - rooms/sala_end.qmd
    - oaks_lab/oaks_lab.qmd
    - oaks_lab/rooms/sala_00.qmd
    - oaks_lab/rooms/sala_01.qmd
    - oaks_lab/rooms/sala_02.qmd
    - oaks_lab/rooms/sala_final.qmd
    - howto.qmd
    - rooms/template.qmd

# Format Configuration
format:
  html:
    theme: sketchy
    css: "style.css"
    number-sections: false
    toc: false
    #page-layout: full
    page-navigation: false
    #sidebar-width: 0px

# Extensions
filters: 
  - pyodide

#sin-enumeracion: true  # Esta línea es opcional para indicar que no se desea enumeración
