# Basic Metadata Configuration
title: "PySchool 2025"
#subtitle: "Un escape room con Python: Aprende Python mientras resuelves desafíos"
#description: "Aprende Python mientras resuelves desafíos"
#author: "Sebastian Flores"
#date: "2025-05-04"
lang: es
license: "CC BY-NC"

# Project Configuration
project:
  type: book
  output-dir: "../docs"

# Book Configuration
book:
  favicon: "images/favicon.png"
  chapters:
    - index.qmd
    - students.qmd
    - part: Estación Espacial 🛰️
      chapters:
        - space_station/space_station.qmd
        - space_station/rooms/sala_00.qmd
        - space_station/rooms/sala_01.qmd
        - space_station/rooms/sala_02.qmd
        - space_station/rooms/sala_03.qmd
        - space_station/rooms/sala_04.qmd
        - space_station/rooms/sala_05.qmd
        - space_station/rooms/sala_06.qmd
        - space_station/rooms/sala_07.qmd
        - space_station/rooms/sala_08.qmd
        - space_station/rooms/sala_09.qmd
        - space_station/rooms/sala_10.qmd
        - space_station/rooms/sala_11.qmd
        - space_station/rooms/sala_12.qmd
        - space_station/rooms/sala_13.qmd
        - space_station/rooms/sala_14.qmd
        - space_station/rooms/sala_15.qmd
        - space_station/rooms/sala_16.qmd
        - space_station/rooms/sala_17.qmd
        - space_station/rooms/sala_final.qmd
    - part: Laboratorio del Profesor Oak 🧪
      chapters:    
        - oaks_lab/oaks_lab.qmd
        - oaks_lab/rooms/sala_00.qmd
        - oaks_lab/rooms/sala_01.qmd
        - oaks_lab/rooms/sala_02.qmd
        - oaks_lab/rooms/sala_03.qmd
        - oaks_lab/rooms/sala_04.qmd
        - oaks_lab/rooms/sala_final.qmd
    - part: Recursos 📚 
      chapters:
        - teachers.qmd
        - pyschool.qmd
        - resources/oaks_lab_solutions.qmd
        - resources/space_station_solutions.qmd
        - resources/howto.qmd
        - resources/template.qmd

# Format Configuration
format:
  html:
    theme: sketchy
    css: "style.css"
    number-sections: false
    toc: false
    page-navigation: false

# Extensions
filters: 
  - pyodide