# Basic Metadata Configuration
title: "PySchool 2025"
#subtitle: "Un escape room con Python: Aprende Python mientras resuelves desafíos"
#description: "Aprende Python mientras resuelves desafíos"
#author: "Sebastian Flores"
#date: "2025-05-04"
lang: es
license: "CC BY-NC"

# Project Configuration
project:
  type: book
  output-dir: "../docs"

# Book Configuration
book:
  sidebar: false        # show sidebar navigation
  #reader-mode: true    # focuses content (like Read the Docs)
  favicon: "images/favicon.png"
  chapters:
    - index.qmd
    - rooms/start.qmd
    - rooms/2.qmd
    - other/autoria.qmd
    - other/cierre_evento.qmd
    - rooms/end.qmd
    - howto.qmd

# Format Configuration
format:
  html:
    theme: sketchy
    css: "style.css"
    number-sections: false
    toc: false
    #page-layout: full
    page-navigation: false
    sidebar-width: 0px

# Extensions
filters: 
  - pyodide

#sin-enumeracion: true  # Esta línea es opcional para indicar que no se desea enumeración
